# Streamlit Secrets (for production)
# Add any API keys or sensitive data here if needed in future

[general]
app_name = "Email Backup Wizard Support"
support_url = "https://emailbackupwizard.com/support.html"

# Example: If you want to add analytics or other services later
# [analytics]
# google_analytics_id = "your-ga-id"
